# Generated by Django 4.2.30 on 2026-04-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("title_ar", models.CharField(blank=True, max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("description", models.TextField()),
                ("description_ar", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="campaigns/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medical", "Medical Treatment"),
                            ("orphan", "Orphan Sponsorship"),
                            ("education", "Education"),
                            ("food", "Food Aid"),
                            ("shelter", "Shelter"),
                            ("water", "Water Projects"),
                            ("zakat", "Zakat"),
                            ("sadaqah", "Sadaqah"),
                            ("waqf", "Waqf"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("donors_count", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("allow_anonymous", models.BooleanField(default=True)),
                (
                    "minimum_donation",
                    models.DecimalField(decimal_places=2, default=10, max_digits=10),
                ),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="charity.charity",
                    ),
                ),
            ],
            options={
                "db_table": "campaign",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
