# Generated by Django 4.2.30 on 2026-04-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_ar", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("description_ar", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="charities/logos/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="charities/covers/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("education", "Education"),
                            ("food", "Food & Water"),
                            ("shelter", "Shelter"),
                            ("orphans", "Orphans"),
                            ("elderly", "Elderly"),
                            ("disability", "People with Disability"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("riyadh", "Riyadh"),
                            ("jeddah", "Jeddah"),
                            ("mecca", "Mecca"),
                            ("medina", "Medina"),
                            ("dammam", "Dammam"),
                            ("khobar", "Al Khobar"),
                            ("taif", "Taif"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("registration_number", models.CharField(blank=True, max_length=50)),
                (
                    "total_raised",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "verbose_name_plural": "charities",
                "db_table": "charity",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
